### ISSUE TITLE
update -selGPU with newer code

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v3.0-windows#37]
NemosMiner-v2.1.ps1
    [Parameter(Mandatory=$false)]
    [Array]$SelGPU = $null, # sample 0..3
    [Parameter(Mandatory=$false)]
    [String]$SelGPUEWBF = "",
    [Parameter(Mandatory=$false)]
    [String]$SelGPUCC = "",
)

  if($SelGPU.Length -ne 0) # Array length test, if not null
   {
     $SelGPUCC = $SelGPU -join "," # "0,1,2,3", If you transfer an array to a string using the $SelGPUCC = $SelGPU will "0 1 2 3"
     $SelGPUCC = " -d $SelGPUCC" # " -d 0,1,2,3"
     $SelGPUEWBF = " --cuda_devices $SelGPU" # " --cuda_devices 0 1 2 3"
    }

Start.bat (with select 0,1,4)
"&.\NemosMiner-v2.1.ps1 -SelGPU 0,1,4 -Currency BTC ...
Start.bat (with select 0)
"&.\NemosMiner-v2.1.ps1 -SelGPU 0 -Currency BTC ...
Start.bat (all cuda device)
"&.\NemosMiner-v2.1.ps1 -Currency BTC

Work all Option. 

ccminerAlexis78.ps1 (сode sample)
"neoscrypt" = "$SelGPUCC -i 15" #NeoScrypt

EWBF.ps1 (сode sample)
    "equihash" = "$SelGPUEWBF" #Equihash

**Comment by nemosminer** [comment]
this will make it  only need -SelGPU instead of -SelGPUCC & -SelGPUDSTM ......

**Comment by barguin** [comment]
Just an idea. Could it be possible to select all GPU if the -selGPU is removed from bat file?
At the moment it will select only one.

Thanks!

**Comment by Dekablade01** [comment]
how about if ignore the `-SelGPU` parameter, mean start mining with all gpu just like ccminer ?

**Comment by nemosminer** [comment]
done auto detect with option of disabling gpu 0
