### ISSUE TITLE
Dedicated Wallet per pool

### ISSUE THREAD

**Issue by lessaid** [nemosminer/NemosMiner-v3.0-windows#383]
Can we have a way to add per pool wallet ?

Let say BTC Internal Nicehash wallet, LTC Zpool etc...

Thx

**Comment by MrPlusGH** [comment]
This feature is available as NM3 shares the same code as NPM2.1
For documentation on how to use refer to NPlusMiner

See changelog for NPlusMiner 2.1 here: [https://github.com/MrPlusGH/NPlusMiner/releases](url)
See NPlusMiner Readme here: [https://github.com/MrPlusGH/NPlusMiner/blob/master/README.md](url)

**Comment by lessaid** [comment]
Got it thx !
