### ISSUE TITLE
I can split GPU 0 to 7 to an instance of Nemos v3 and gpu 8 to 12 to another one ?

### ISSUE THREAD

**Issue by Zarce** [nemosminer/NemosMiner-v3.0-windows#384]
Hi.
I can split GPU 0-7 to an instance of Nemos v3 and gpu 8-12 to another one?
Because of the limitation of same ccminer versions, i think the old ones, but still good on hash result, i need or split in two instances of Nemosminer. In this rig i have 13 GPUs same type.

I have another rig with two different gpu type, and want to split for better result after benckmark.

Thank you !

**Comment by MrPlusGH** [comment]
NPlusMiner supports running multiple instances.
[https://github.com/MrPlusGH/NPlusMiner/releases](url)
