### ISSUE TITLE
Nicehash Internal

### ISSUE THREAD

**Issue by uprise88** [nemosminer/NemosMiner-v3.0-windows#386]
I love the way the new config file works, so i can mine on Zpool and Nicehash internal wallet.

My question now is how can i set the payment thershold for nicehash internal form 0.01 to 0.001?

Thx

**Comment by MrPlusGH** [comment]
Nemo would need to update data for NemosMiner.
NPlusMiner is up to date on pools payments threshold.
[https://github.com/MrPlusGH/NPlusMiner/releases](url)

**Comment by uprise88** [comment]
Thx! Can i use same stat folder from nemos ti nplus?

**Comment by tiotoi** [comment]
@uprise88 good question!

**Comment by MrPlusGH** [comment]
Yes

**Comment by nemosminer** [comment]
Yes

**Comment by nemosminer** [comment]
fixed : http://nemosminer.x10host.com/poolapiref.json

**Comment by uprise88** [comment]
THX!
