### ISSUE TITLE
6 GPUs detected, but only 2 used

### ISSUE THREAD

**Issue by pjdouillard** [nemosminer/NemosMiner-v3.0-windows#389]
How do I specify to use all GPUs and just just GPU 0 and 1?

**Comment by nemosminer** [comment]
hi just going to get some breakfast i will download a fresh copy of v3.0 and run it through my 6x1080ti rig and get back to you 
should be any longer than a hour...

**Comment by pjdouillard** [comment]
I am making supper here! :)  Thx Nemo!

**Comment by nickvasel** [comment]
Have same issue, removing the back file did not work....

**Comment by nemosminer** [comment]
You need to switch to manual config for this type of advanced configuration.
Edit \config\config.json
Change lines accordingly:
    "SelGPUDSTM":  "1 2 3 4",
    "SelGPUCC":  "1,2,3,4",
Restart NemosMiner.

Note that once you switch to manual config edit you must not use the GUI config anymore. Stick to manual edits.
Click "Save Config" would overwrite your changes.

**Comment by nickvasel** [comment]
I checked both config.json and config.json.back they showed correct:
"SelGPUCC": "0,1,2,3,4,5",
 "SelGPUDSTM": "0 1 2 3 4 5",
restarted and seems to be working on all 6 now. Will keep you posted....
Thanks again...

**Comment by nemosminer** [comment]
:  )
