### ISSUE TITLE
Benchmarking on pools not chosen?

### ISSUE THREAD

**Issue by pjdouillard** [nemosminer/NemosMiner-v3.0-windows#391]
I would like to know why we are benching algo's on pools that we don't have account on and have not selected?

**Comment by MrPlusGH** [comment]
Did you hit save config?
Could you share your config file?

**Comment by pjdouillard** [comment]
The config has:
   "PoolName":  [
                     "ahashpoolplus",
                     "zergpoolplus",
                     "miningpoolhub"
                 ],

although I only checked miningpoolhub and then saved the config.

**Comment by MrPlusGH** [comment]
So you kept the default selection and added MPH then.
You need to unselect the others if your don't want them.

**Comment by pjdouillard** [comment]
I will used the text file for further config as the gui is misleading to what I have done.

**Comment by MrPlusGH** [comment]
Not saying you did anything wrong.
Could you expand on what's confusing?
There might be something to fix or make easier to understand.

**Comment by nemosminer** [comment]
you need to selected the pool you want to use by default it will be ahashpool plus zergpoolplus & nicehash

no issue here...
