### ISSUE TITLE
MSVCR120.dll - not working even after d/l package from MS

### ISSUE THREAD

**Issue by pjdouillard** [nemosminer/NemosMiner-v3.0-windows#392]
I had installed (and re-installed) the package from Microsoft you pointed, but I still get a crash when ccminer starts because it can't find it.  When I search on disk, I see msvcr120_clr0400.dll where it should be, and also msvcr120.dll in the c:\windows\syswow64 and c:\windows\system folderrs.

So I am wondering are you sure your code isn't just looking in the application's own folder, and not the system or wow64 folders?

**Comment by pjdouillard** [comment]
I have manually added the msvcr120.dll to the Alexis78Phi folder.
I then started manually that ccminer and the error for finding the dll is gone, but some other error pops up statng 'The application was unable to start correctly (0xc000007b).

So that tells me this ccminer version was compiled with the run time dll in its directly and is not using the global path for system dll.

**Comment by nemosminer** [comment]
which ccminer is that happening with ccminerphi? i don't get that i have 11 different rigs all running different cards and different versions of win10....

**Comment by nemosminer** [comment]
no issue here..

**Comment by nemosminer** [comment]
if its just ccminerphi disable it and enable phi with ccminertpruvot there speed is very similar...
