### ISSUE TITLE
Incorretly Dectecting GPU0

### ISSUE THREAD

**Issue by termonator145** [nemosminer/NemosMiner-v3.0-windows#393]
Hello!
Not sure if this was intended or if there is any way around it...
In my rig, I am running a GTX 660Ti for my main gpu/display output on the first PCI slot, and a 1080 in the second slot dedicated to mining. 

Windows correctly determines that GPU0 is the 660, and GPU1 is the 1080, but using miner 3.0, 2.5.2, and 2.4.2, the 2 are reversed in there. (1080 becomes GPU0, 660 becomes GPU1)

Any possibility this can be resolved, or is this intended operation?

**Comment by MrPlusGH** [comment]
CUDA does not rely on PCI addressing for ordering. 
Unfortunately, we cannot do anything to fix this right now.
