### ISSUE TITLE
Error Get HashRate

### ISSUE THREAD

**Issue by thel3lue** [nemosminer/NemosMiner-v3.0-windows#394]
https://imgur.com/o5P3dDo
get this error can't finish benchmark 
may i know how to fix it?

**Comment by MrPlusGH** [comment]
404 on your link so don't get the error

**Comment by nemosminer** [comment]
try now.. still adding updates

**Comment by thel3lue** [comment]
https://imgur.com/rY3qshg

**Comment by nemosminer** [comment]
1050ti...
