### ISSUE TITLE
Nemos Miner 3.0 - each miner launch fails

### ISSUE THREAD

**Issue by NoKwarl** [nemosminer/NemosMiner-v3.0-windows#397]
I hate writing bugs like this - but the first few times I ran NemosMiner 3.0 (as of 9:30AM EST 3-16-2018 from current branch) - three start up attempts failed to run a miner. Then, I stopped it, ran Nemos Miner 2.5.2 for a minutes, stopped that. Then, I started NemosMiner 3.0, and it successfully started and is benchmarking (currently NeoScript).

As it is I don't know why it was failing the first few runs.

**Comment by nemosminer** [comment]
thanks
