### ISSUE TITLE
Feature request: NemosMiner GUI auto-save config after edit, add revert changes to default

### ISSUE THREAD

**Issue by NoKwarl** [nemosminer/NemosMiner-v3.0-windows#398]
When I first ran the GUI I added the wallet but did not note I had to click the Save button. When I ran it, it obviously started to mine to the dev wallet on the preferred dev pool. Can this be auto saved, or can a prompt be added to choose to save the changes or revert to previous when starting mining to make this more obvious?

**Comment by MrPlusGH** [comment]
Autosave is a no. Would lead to people making mistakes and getting messy configuration.
Might look at adding a popup. No promess
