### ISSUE TITLE
Second pool not displayed 

### ISSUE THREAD

**Issue by bit2017user** [nemosminer/NemosMiner-v3.0-windows#405]
Hi
I have chosen 2 pools to try this option but the second pool is not displayed in the gui
in the run section

![v3a](https://user-images.githubusercontent.com/37226252/37545229-5a11878c-2968-11e8-8d58-da7736efd27b.jpg)

![v3](https://user-images.githubusercontent.com/37226252/37545223-4c1f114e-2968-11e8-99b3-6b9cc936446c.jpg)

**Comment by nemosminer** [comment]
if both pools use the same algo, it will only show the profitable one
